jobs:
  deploy:
    runs-on: ubuntu-latest  # Or another runner depending on your environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This checks out your code from the repository

      - name: Set up Python 3.x  # Ensuring Python is set up if needed
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies from requirements.txt
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Ensure dependencies are installed before deploying

      - name: Make deploy.sh executable
        run: chmod +x ./deploy.sh  # Ensure deploy.sh has executable permissions

      - name: Run deployment script
        run: ./deploy.sh  # Run the custom deployment script
        env:
          DEPLOY_ENV: production  # You can pass environment variables to your script here
